notifications:
    slack: wtsi-cgpit:ABlfGMqViryJ0JIhJuaWeXDa

sudo: false

services:
    - docker

script:
- set -e
- echo 'Build and check docker image'
- docker build -t sigprofiler-travis .
- docker images | grep -c sigprofiler-travis
- docker run -t --rm sigprofiler-travis docker-sigprofiler --version
